// All Actions for the application
export default {
    ADD_DAY: "ADD_DAY",
    REMOVE_DAY: "REMOVE_DAY",
    SET_GOAL: "SET_GOAL",
    UPDATE_STREAK: "UPDATE_STREAK",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    FETCH_WORKOUT_TARGETS: "FETCH_WORKOUT_TARGETS",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",
    SUGGEST_TARGET_NAMES: "SUGGEST_TARGET_NAMES"
}
